# Generated by Django 4.1.7 on 2023-05-12 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Primeiro Nome', models.CharField(max_length=100)),
                ('Segundo Nome', models.CharField(max_length=150)),
                ('Telefone', models.CharField(max_length=9)),
                ('Email', models.EmailField(blank=True, max_length=256)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField(blank=True, default='Descrição')),
            ],
        ),
    ]
