# Generated by Django 4.1.7 on 2023-05-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0002_alter_contato_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='descricao',
        ),
        migrations.AddField(
            model_name='contato',
            name='Descrição',
            field=models.TextField(blank=True),
        ),
    ]
