# Generated by Django 4.1.7 on 2023-05-12 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0003_remove_contato_descricao_contato_descrição'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='Primeiro Nome',
            new_name='Nome',
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='Segundo Nome',
            new_name='Sobrenome',
        ),
    ]
