# Generated by Django 4.2.1 on 2023-05-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0004_rename_primeiro nome_contato_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='Descrição',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='Nome',
            new_name='primeiro_nome',
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='Sobrenome',
            new_name='segundo_nome',
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='Telefone',
            new_name='telefone',
        ),
    ]
