# Generated by Django 4.2.1 on 2023-05-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0005_rename_descrição_contato_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='contato',
            name='visivel',
            field=models.BooleanField(default=True),
        ),
    ]
