# Generated by Django 4.1.7 on 2023-05-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0008_alter_categoria_options_contato_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(max_length=50),
        ),
    ]
